### ISSUE TITLE
No "YBCA" entity

### ISSUE THREAD

**Issue by workergnome** [american-art/YCBA#2]
I'm not sure that there's a base entity in your data for YCBA itself, or at least that entity is not the `?owner` of the `?work crm:P52_has_current_owner ?owner`.  Instead, you're pointing to the ULAN entity for YCBA.

How hard would it be to change this to be a URI that you own, and that has basic metadata (such as a `skos:exactMatch` to ULAN, and  a preferred ID, and a label.)

See http://data.americanartcollaborative.org/page/GM for a stub.  (They don't have a preferred ID, which means that the Browse App doesn't know how to assign it a prettier URI, but that's not a dealbreaker)

**Comment by mikeapp** [comment]
Sure, we can do this.  I plan to have an updated data set for the Center by Friday.

**Comment by caknoblock** [comment]
This graph shows how the owner is modeled in GM:

https://github.com/american-art/GM/blob/master/Objects/Objects-model.pdf <https://github.com/american-art/GM/blob/master/Objects/Objects-model.pdf>

**Comment by mikeapp** [comment]
This also impacts the acquisition events, no?

**Comment by workergnome** [comment]
Very possibly--I can check if you like. (You're the only people with robust acquisition modeling). 
		
		

		
	




On Fri, Jul 21, 2017 at 8:38 AM -0700, "mikeapp" <notifications@github.com> wrote:












This also impacts the acquisition events, no?

**Comment by mikeapp** [comment]
I'll assume it's preferable to have:
`<acquisition event>  erl:P22_transferred_title_to  <new YCBA legal entity instead of ULAN ID>`

**Comment by edgartdata** [comment]
How about the custody of the works in addition to the ownership title?

**Comment by workergnome** [comment]
That would be lovely, too—probably in the same acquisition event, which would have both a P22 and a P29?

**Comment by edgartdata** [comment]
Exactly!

**Comment by mikeapp** [comment]
Sure, we have both P22 and P29 in our source data.

**Comment by mikeapp** [comment]
I've uploaded a test set of about 18K records.  Generating the full set is taking longer than anticipated, it should be ready early next week.

**Comment by mikeapp** [comment]
Uploaded the full set, about 58K records.

**Comment by workergnome** [comment]
Thanks!  @caknoblock, can you post a comment here when they're in the triple store?

**Comment by caknoblock** [comment]
The data has now been uploaded.
Craig

**Comment by kateblanch** [comment]
What is the best way to test this? 
Duh alert :) -- When I navigate to http://data.americanartcollaborative.org/page/YCBA/ I get a 404. Am I using the wrong domain?

**Comment by edgartdata** [comment]
I think we are using our own URI, such as http://collection.britishart.yale.edu/id/page/object/173

**Comment by edgartdata** [comment]
sorry this is the correct URI pattern: http://collection.britishart.yale.edu/id/object/173

**Comment by kateblanch** [comment]
And I AM sorry for coming into this late in the game. I am unsure if the expectation is that every partner has an owner page (e.g. http://data.americanartcollaborative.org/page/GM) -- some partners have a working URI for their institutions, and some partners return 404s using that pattern. Let me do some background research as this affects more than just YCBA.

**Comment by workergnome** [comment]
@edgartdata:  This is the sparql query that determines if you're an institution or not:

http://yasgui.org/short/S1FT--aaW

**Comment by mikeapp** [comment]
Query from @workergnome looks good in my local Blazegraph instance.  

<img width="1136" alt="screen shot 2017-10-24 at 3 16 44 pm" src="https://user-images.githubusercontent.com/1987952/31963388-77881638-b8ce-11e7-9b26-fae817dddc12.png">

**Comment by workergnome** [comment]
Great.  Then I think it's just a data update from ISI and that problem will resolve itself.

**Comment by edgartdata** [comment]
@workergnome  Should I let Craig know to refresh YCBA data in their triplestore?

**Comment by edgartdata** [comment]
Hi @caknoblock, can you refresh the YCBA data please?

**Comment by caknoblock** [comment]
Yes, should happen in the next day or two.
Craig

**Comment by GreatYYX** [comment]
refreshed
